import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Toks
        </h1>
        <button type="button" onClick={() => {
          throw new Error("프론트엔드 에러!!55");
        }}>
            위험..!
        </button>
      </main>
    </div>
  )
}

export default Home
